### PR TITLE
FAI-682: PF: Select/SelectOption regression

### PR DESCRIPTION
**Pull request by kelvah**
JIRA: https://issues.redhat.com/browse/FAI-682

### CODE REVIEW

**Comment by kelvah** [comment]
hi @caponetto,
opening this PR to fix the Select regression.

@manstis could you please confirm the workaround works O.K.? thanks.

**Comment by caponetto** [comment]
Thanks, @kelvah!
Let's wait for @manstis feedback and green CI.

**Comment by tiagobento** [comment]
@kelvah Thanks for the fix!! I think we can reanable the test too.

**Comment by caponetto** [comment]
Green!
I'll go ahead and merge this one, and re-enable the test.

**Comment by manstis** [comment]
Clearly I'm late to the party; but I can confirm the workaround works well. Thank-you @kelvah :1st_place_medal:

**Pull request merged**
